# Welcome to Jekyll!
#
title: Create your own coding companion
email:
description: >- # this means to ignore newlines until "baseurl:"
  Coding is better with friends, especially when they bring their own mods. As the mascot for the .NET community, dotnet-bot helps with checking pull requests on .NET repos on GitHub. Create your own custom coding companion by modding the dotnet-bot.
#baseurl: "/mod-dotnet-bot" # the subpath of your site, e.g. /blog
url: "https://mod-dotnet-bot.net" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

defaults:
  -
    scope:
      path: ""
    values:
      image: assets/images/social-card.png
      layout: default
      is_post: true
